"""Investment income in ratemaking — insurance vs investment operations.

Chapter 5: a property/casualty insurer is really two operations. The insurance
operations write policies, collect premiums, and pay losses; the investment
operations use the funds generated by the insurance operations to buy bonds,
stocks, and other investments to earn an investment profit. Insurers today
commonly consider investment results explicitly in their rate calculations, and
some states require it. Investment profit depends largely on the loss reserves
and unearned premium reserves. Because liability losses are paid years after
they occur, liability loss reserves — and therefore investment income — are much
greater than for an equivalent amount of property insurance.

This module makes that explicit: for each line it estimates the reserve funding
(and hence investable funds) relative to premium, applies an expected investment
yield, and reports how much the investment income can offset the required rate.
Lines where a state requires investment income to be considered explicitly are
flagged.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from insureflow.models.agents import RiskSeverity
from insureflow.rating.models import InsuranceLine


class LossTail(str, Enum):
    SHORT = "short"
    LONG = "long"
    NOT_APPLICABLE = "not_applicable"


# Reserve funding as a multiple of annual premium: loss reserves plus unearned
# premium reserves held on average during the year. Long-tail liability lines
# hold far more reserve funding than short-tail property lines.
_LINE_TAIL: dict[str, tuple[LossTail, float, float, str]] = {
    "commercial_property": (LossTail.SHORT, 0.25, 0.15, "Property losses paid quickly; small investable reserve"),
    "general_liability": (LossTail.LONG, 1.10, 0.20, "Liability losses paid years after occurrence; large investable reserve"),
    "workers_comp": (LossTail.LONG, 0.90, 0.20, "Long-tail indemnity and medical payments; heavy reserve funding"),
    "business_owners_policy": (LossTail.SHORT, 0.30, 0.20, "Packaged property exposure; moderate reserve funding"),
    "umbrella": (LossTail.LONG, 1.30, 0.15, "Excess liability — the longest tail; largest reserve funding"),
    "personal_homeowners": (LossTail.SHORT, 0.15, 0.15, "Short-tail property; minimal reserve funding"),
    "personal_auto": (LossTail.SHORT, 0.45, 0.20, "Mixed: liability balances short-tail physical damage"),
    "life": (LossTail.NOT_APPLICABLE, 0.0, 0.0, "Life is priced through its own long-tail mechanics, outside this P&C chapter"),
}

# Examples of states that require investment income to be considered explicitly
# in rate filings. (Set is illustrative of the textbook's "some states require".)
_STATES_REQUIRING_EXPLICIT: frozenset[str] = frozenset({"NY", "NJ", "MA", "FL", "PA", "IL"})

_DEFAULT_YIELD = 0.04


class InvestmentIncomeAssessment(BaseModel):
    """Explicit investment-income consideration for a single line."""

    line: str
    tail: LossTail = LossTail.SHORT
    loss_reserve_funding: float = 0.0
    unearned_premium_reserve_funding: float = 0.0
    yield_rate: float = _DEFAULT_YIELD
    investment_income_pct_of_premium: float = 0.0
    rate_offset_pct: float = 0.0
    state_requires_explicit: bool = False
    note: str = ""
    detail: str = ""


def states_requiring_explicit_investment_income() -> list[str]:
    """States that require investment income to be considered explicitly."""
    return sorted(_STATES_REQUIRING_EXPLICIT)


def line_investment_profile(line: InsuranceLine) -> tuple[LossTail, float, float, str]:
    """Reserve-funding profile (tail, loss-reserve funding, UPR funding, note)."""
    return _LINE_TAIL.get(line.value, (LossTail.SHORT, 0.2, 0.15, "Default short-tail profile"))


def assess_investment_income(
    line: InsuranceLine,
    *,
    yield_rate: float = _DEFAULT_YIELD,
    state: Optional[str] = None,
) -> InvestmentIncomeAssessment:
    """Explicit investment income for a line's reserve funding.

    Investment income as a share of premium equals the total reserve funding
    (loss reserves + unearned premium reserves) times the expected investment
    yield. That income can offset the premium the insurer must collect, so the
    indicated rate offset is the same percentage. Long-tail liability lines —
    with much larger reserves — show a materially larger offset than short-tail
    property lines.
    """
    tail, reserve_funding, upr_funding, note = line_investment_profile(line)
    total_funding = reserve_funding + upr_funding
    income_pct = round(total_funding * yield_rate * 100.0, 2)
    requires = state is not None and state.upper() in _STATES_REQUIRING_EXPLICIT
    offset = round(income_pct, 2) if tail is not LossTail.NOT_APPLICABLE else 0.0
    return InvestmentIncomeAssessment(
        line=line.value,
        tail=tail,
        loss_reserve_funding=reserve_funding,
        unearned_premium_reserve_funding=upr_funding,
        yield_rate=round(yield_rate, 4),
        investment_income_pct_of_premium=round(income_pct, 2),
        rate_offset_pct=offset,
        state_requires_explicit=requires,
        note=note,
        detail=(
            f"{tail.value} tail: {(reserve_funding + upr_funding) * 100:.0f}% of premium invested "
            f"at {yield_rate:.1%} → {income_pct:.1f}% of premium from investments" + ("; state requires explicit consideration" if requires else "")
        ),
    )


def investment_income_across_lines(*, yield_rate: float = _DEFAULT_YIELD, state: Optional[str] = None) -> list[InvestmentIncomeAssessment]:
    """Explicit investment-income assessment across all rating lines."""
    return [assess_investment_income(line, yield_rate=yield_rate, state=state) for line in InsuranceLine]


def investment_income_severity(assessment: InvestmentIncomeAssessment, state: Optional[str] = None) -> RiskSeverity:
    """How much the investment offset matters for the rate.

    Long-tail lines and states requiring explicit consideration raise the
    stakes: ignoring the offset overstates the required rate.
    """
    if assessment.state_requires_explicit and assessment.rate_offset_pct >= 2.0:
        return RiskSeverity.HIGH
    if assessment.tail is LossTail.LONG and assessment.rate_offset_pct >= 2.0:
        return RiskSeverity.MODERATE
    return RiskSeverity.LOW
