/** Top-level Insurance IA — 12 sections matching the product taxonomy. */

export const INSURANCE_SECTIONS = [
  {
    id: 'life',
    n: 1,
    title: 'Life Insurance',
    summary: 'Pure protection, cash-value, savings, market-linked, and retirement income.',
    status: 'live',
    hub: '/insurance/life',
    accent: 'rose',
    icon: 'HeartPulse',
    products: [
      { name: 'Term life', hint: 'Pure protection for a fixed period', href: '/insurance/life/level-term' },
      { name: 'Whole life', hint: 'Lifelong coverage with a cash-value component', href: '/insurance/life/traditional-whole-life' },
      { name: 'Endowment plans', hint: 'Insurance + maturity savings', href: '/insurance/life/full-with-profit-endowment' },
      { name: 'ULIPs', hint: 'Life cover + market-linked investment', href: '/insurance/life/regular-premium-ulip' },
      { name: 'Money-back policies', hint: 'Periodic payouts during the term', href: '/insurance/life/traditional-money-back' },
      { name: 'Annuities / pension', hint: 'Income after retirement', href: '/insurance/life/immediate-annuity' },
    ],
  },
  {
    id: 'health',
    n: 2,
    title: 'Health Insurance',
    summary: 'Individual, family, critical illness, senior, group, top-up, PA, and disability.',
    status: 'catalog',
    hub: '/insurance/health',
    accent: 'teal',
    icon: 'Stethoscope',
    products: [
      { name: 'Individual health', hint: 'Mediclaim for a single insured', href: '/insurance/health/individual-basic' },
      { name: 'Family floater', hint: 'Shared sum insured across the family', href: '/insurance/health/family-floater-standard' },
      { name: 'Critical illness', hint: 'Lump-sum on listed diagnoses', href: '/insurance/health/critical-illness-standalone' },
      { name: 'Senior citizen health', hint: 'Age-banded hospital cover', href: '/insurance/health/senior-standard' },
      { name: 'Group / corporate health', hint: 'Employer or affinity mediclaim', href: '/insurance/health/group-employer-mediclaim' },
      { name: 'Top-up / super top-up', hint: 'Extra cover above a base limit', href: '/insurance/health/super-topup-plan' },
      { name: 'Personal accident', hint: 'Accidental death & disablement', href: '/insurance/health/pa-individual' },
      { name: 'Disability insurance', hint: 'PTD / PPD / TTD / income protection', href: '/insurance/health/disability-income' },
    ],
  },
  {
    id: 'general',
    n: 3,
    title: 'General / Non-Life',
    summary: 'Motor, home, travel, marine, fire, liability, and cyber — TP vs comprehensive, cargo vs hull.',
    status: 'catalog',
    hub: '/insurance/general',
    accent: 'sky',
    icon: 'Umbrella',
    filterCategories: ['motor', 'home', 'travel', 'marine', 'fire', 'liability', 'cyber'],
    hubKind: 'general',
    products: [
      { name: 'Motor', hint: 'Car, two-wheeler, CV — third-party and comprehensive', href: '/insurance/general/car-tp' },
      { name: 'Home / property', hint: 'Structure, contents, or both', href: '/insurance/general/home-comprehensive' },
      { name: 'Travel', hint: 'Domestic and international', href: '/insurance/general/travel-international' },
      { name: 'Marine', hint: 'Cargo and hull for shipping', href: '/insurance/general/marine-cargo' },
      { name: 'Fire', hint: 'Fire and allied perils', href: '/insurance/general/fire-residential' },
      { name: 'Liability', hint: 'PI, public, and product liability', href: '/insurance/general/professional-indemnity-gi' },
      { name: 'Cyber', hint: 'Data breach and cyberattack / ransomware', href: '/insurance/general/cyber-data-breach' },
    ],
  },
  {
    id: 'commercial',
    n: 4,
    title: 'Business / Commercial',
    summary: 'Property & BI, D&O, workers’ comp, trade credit, E&O, and key person.',
    status: 'live',
    hub: '/insurance/commercial',
    accent: 'brand',
    icon: 'Briefcase',
    hubKind: 'commercial',
    filterIds: ['property_bi', 'directors_officers', 'workers_comp', 'trade_credit', 'errors_omissions', 'key_person'],
    products: [
      { name: 'Property & business interruption', hint: 'Buildings, contents, and BI', href: '/insurance/commercial/property-bi' },
      { name: 'Directors & Officers (D&O)', hint: 'Management liability', href: '/insurance/commercial/do' },
      { name: "Workers' compensation", hint: 'Employee injury / occupational disease', href: '/insurance/commercial/workers-comp' },
      { name: 'Trade credit', hint: 'Buyer default on receivables', href: '/insurance/commercial/trade-credit' },
      { name: 'Errors & Omissions (E&O)', hint: 'Professional services negligence', href: '/insurance/commercial/eo' },
      { name: 'Key person', hint: 'Cover on a critical employee', href: '/insurance/commercial/key-person' },
    ],
  },
  {
    id: 'specialty',
    n: 5,
    title: 'Other / Specialty',
    summary: 'Crop, livestock, pet, events, title, and mortgage — subject-matter docs, not generic KYC alone.',
    status: 'catalog',
    hub: '/insurance/general',
    accent: 'amber',
    icon: 'Leaf',
    filterCategories: ['crop', 'animal', 'event', 'title', 'mortgage_gi'],
    hubKind: 'general',
    products: [
      { name: 'Crop insurance', hint: 'Yield-based and weather-index', href: '/insurance/general/crop-yield' },
      { name: 'Livestock / cattle', hint: 'Vet cert, tag, valuation', href: '/insurance/general/livestock-cattle' },
      { name: 'Pet insurance', hint: 'Vaccination and medical history', href: '/insurance/general/pet-insurance' },
      { name: 'Event insurance', hint: 'Weddings, concerts, public events', href: '/insurance/general/wedding-insurance' },
      { name: 'Title insurance', hint: 'Deed chain, encumbrance, title search', href: '/insurance/general/title-insurance' },
      { name: 'Mortgage insurance', hint: 'Lender-linked cover on the loan / property', href: '/insurance/general/mortgage-insurance-gi' },
    ],
  },
  {
    id: 'provider',
    n: 6,
    title: 'By Provider Type',
    summary: 'PSU vs private purchase KYC, and B2B reinsurance. Bancassurance is a bank distribution channel.',
    status: 'catalog',
    hub: '/insurance/general',
    accent: 'violet',
    icon: 'Landmark',
    filterCategories: ['provider'],
    hubKind: 'general',
    products: [
      { name: 'Public sector insurers', hint: 'Govt-backed — strict KYC, often Aadhaar-linked', href: '/insurance/general/insurer-psu' },
      { name: 'Private insurers', hint: 'e-KYC; income proof for higher SI', href: '/insurance/general/insurer-private' },
      { name: 'Reinsurance companies', hint: 'Insurance for insurers — treaty / facultative, not retail KYC', href: '/insurance/general/reinsurance-treaty' },
      { name: 'Bancassurance', hint: 'Distribution channel (sold through banks), not a product type', href: '/insurance/sections/provider' },
    ],
  },
  {
    id: 'engineering',
    n: 7,
    title: 'Engineering Insurance',
    summary: 'Construction, erection, machinery, boiler, and advance loss of profit.',
    status: 'catalog',
    hub: '/insurance/commercial',
    accent: 'orange',
    icon: 'HardHat',
    hubKind: 'commercial',
    filterIds: ['construction', 'builders_risk', 'equipment_breakdown', 'business_interruption'],
    products: [
      { name: "Contractor's All Risk (CAR)", hint: 'Covers construction projects', href: '/insurance/commercial/construction' },
      { name: 'Erection All Risk (EAR)', hint: 'Machinery installation / erection', href: '/insurance/commercial/construction' },
      { name: 'Machinery breakdown', hint: 'Sudden mechanical / electrical failure', href: '/insurance/commercial/equipment-breakdown' },
      { name: 'Boiler & pressure plant', hint: 'Explosion / collapse of pressure equipment', href: '/insurance/commercial/equipment-breakdown' },
      { name: 'Advance Loss of Profit (ALOP)', hint: 'Delay in start-up after a CAR/EAR loss', href: '/insurance/commercial/business-interruption' },
    ],
  },
  {
    id: 'aviation',
    n: 8,
    title: 'Aviation Insurance',
    summary: 'Aircraft hull, liability, and passenger risk.',
    status: 'catalog',
    hub: '/insurance/commercial/aviation',
    accent: 'indigo',
    icon: 'Plane',
    hubKind: 'commercial',
    filterIds: ['aviation'],
    products: [
      { name: 'Aircraft hull', hint: 'Physical damage to the aircraft', href: '/insurance/commercial/aviation' },
      { name: 'Aviation liability', hint: 'Third-party BI / PD from aircraft operations', href: '/insurance/commercial/aviation' },
      { name: 'Passenger liability', hint: 'Passenger injury / death risk', href: '/insurance/commercial/aviation' },
    ],
  },
  {
    id: 'fidelity',
    n: 9,
    title: 'Fidelity & Burglary',
    summary: 'Employee dishonesty / fraud, and burglary / theft of property.',
    status: 'catalog',
    hub: '/insurance/commercial/crime',
    accent: 'fuchsia',
    icon: 'Lock',
    hubKind: 'commercial',
    filterIds: ['crime'],
    products: [
      { name: 'Fidelity guarantee', hint: 'Employee dishonesty / fraud', href: '/insurance/commercial/crime' },
      { name: 'Burglary / theft', hint: 'Forcible entry and theft of contents', href: '/insurance/commercial/crime' },
    ],
  },
  {
    id: 'catastrophe',
    n: 10,
    title: 'Catastrophe / Natural Disaster',
    summary: 'Flood, earthquake, and parametric / weather-index triggers.',
    status: 'catalog',
    hub: '/insurance/commercial',
    accent: 'cyan',
    icon: 'CloudRain',
    hubKind: 'mixed',
    products: [
      { name: 'Flood insurance', hint: 'Inundation damage to property', href: '/insurance/commercial/flood-commercial' },
      { name: 'Earthquake insurance', hint: 'Shake, fire-following, and sprinkler leakage', href: '/insurance/commercial/earthquake-commercial' },
      { name: 'Parametric / weather-index', hint: 'Payout from weather data, not loss adjustment', href: '/insurance/general/crop-weather' },
    ],
  },
  {
    id: 'niche-liability',
    n: 11,
    title: 'Niche Liability Covers',
    summary: 'Umbrella, pollution, K&R, political risk, and terrorism.',
    status: 'catalog',
    hub: '/insurance/commercial',
    accent: 'emerald',
    icon: 'Scale',
    hubKind: 'commercial',
    filterIds: ['umbrella', 'pollution', 'kidnap_ransom', 'political_risk', 'terrorism'],
    products: [
      { name: 'Umbrella insurance', hint: 'Extra liability above existing limits', href: '/insurance/commercial/umbrella' },
      { name: 'Environmental / pollution liability', hint: 'Pollution incidents and cleanup', href: '/insurance/commercial/pollution' },
      { name: 'Kidnap & ransom (K&R)', hint: 'Kidnap, extortion, and related crisis costs', href: '/insurance/commercial/kidnap-ransom' },
      { name: 'Political risk', hint: 'Expropriation, transfer, and political violence', href: '/insurance/commercial/political-risk' },
      { name: 'Terrorism insurance', hint: 'Certified terrorism property / liability', href: '/insurance/commercial/terrorism' },
    ],
  },
  {
    id: 'warranty-financial-emerging',
    n: 12,
    title: 'Warranty, Financial & Emerging',
    summary: 'Extended warranty, surety, gadget & jewelry, legal expense, credit life, bancassurance, micro, on-demand, UBI, personal cyber.',
    status: 'catalog',
    hub: '/insurance/commercial',
    accent: 'slate',
    icon: 'ShieldCheck',
    hubKind: 'mixed',
    products: [
      { name: 'Extended warranty', hint: 'Electronics, appliances, vehicles beyond OEM warranty', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'Surety bonds', hint: 'Guarantees contract performance (adjacent to insurance)', href: '/insurance/commercial/surety-bonds' },
      { name: 'Gadget / mobile insurance', hint: 'Phones, laptops, wearables — theft, damage, liquid', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'Jewelry / valuables', hint: 'Scheduled high-value personal articles', href: '/insurance/general/home-contents' },
      { name: 'Legal expense insurance', hint: 'Legal costs and defence', href: '/insurance/commercial/legal-expense' },
      { name: 'Credit life', hint: 'Pays off a loan if the borrower dies', href: '/insurance/life/credit-life' },
      { name: 'Bancassurance', hint: 'Insurance sold through banks (channel, not a product)', href: '/insurance/sections/provider' },
      { name: 'Microinsurance', hint: 'Low-premium, low-cover plans for low-income groups', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'On-demand insurance', hint: 'Pay-per-use — a single trip or item', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'Usage-based motor (telematics)', hint: 'Premium tied to actual driving behaviour', href: '/insurance/general/car-comprehensive' },
      { name: 'Personal cyber', hint: 'Identity theft and online fraud for individuals', href: '/insurance/general/cyber-data-breach' },
    ],
  },
];

export function getInsuranceSection(id) {
  return INSURANCE_SECTIONS.find((s) => s.id === id) || null;
}

export function insuranceSectionAccent(accent) {
  const map = {
    rose: { ring: 'hover:ring-rose-400/40', iconBg: 'bg-rose-500/15 text-rose-400', tag: 'text-rose-400', num: 'text-rose-400/80' },
    teal: { ring: 'hover:ring-teal-400/40', iconBg: 'bg-teal-500/15 text-teal-400', tag: 'text-teal-400', num: 'text-teal-400/80' },
    sky: { ring: 'hover:ring-sky-400/40', iconBg: 'bg-sky-500/15 text-sky-400', tag: 'text-sky-400', num: 'text-sky-400/80' },
    brand: { ring: 'hover:ring-brand/40', iconBg: 'bg-brand/15 text-brand', tag: 'text-brand', num: 'text-brand/80' },
    amber: { ring: 'hover:ring-amber-400/40', iconBg: 'bg-amber-500/15 text-amber-400', tag: 'text-amber-400', num: 'text-amber-400/80' },
    violet: { ring: 'hover:ring-violet-400/40', iconBg: 'bg-violet-500/15 text-violet-400', tag: 'text-violet-400', num: 'text-violet-400/80' },
    orange: { ring: 'hover:ring-orange-400/40', iconBg: 'bg-orange-500/15 text-orange-400', tag: 'text-orange-400', num: 'text-orange-400/80' },
    indigo: { ring: 'hover:ring-indigo-400/40', iconBg: 'bg-indigo-500/15 text-indigo-400', tag: 'text-indigo-400', num: 'text-indigo-400/80' },
    fuchsia: { ring: 'hover:ring-fuchsia-400/40', iconBg: 'bg-fuchsia-500/15 text-fuchsia-400', tag: 'text-fuchsia-400', num: 'text-fuchsia-400/80' },
    cyan: { ring: 'hover:ring-cyan-400/40', iconBg: 'bg-cyan-500/15 text-cyan-400', tag: 'text-cyan-400', num: 'text-cyan-400/80' },
    emerald: { ring: 'hover:ring-emerald-400/40', iconBg: 'bg-emerald-500/15 text-emerald-400', tag: 'text-emerald-400', num: 'text-emerald-400/80' },
    slate: { ring: 'hover:ring-slate-400/40', iconBg: 'bg-slate-500/15 text-slate-300', tag: 'text-slate-300', num: 'text-slate-400' },
  };
  return map[accent] || map.slate;
}
