/** Top-level Insurance IA — 12 sections matching the product taxonomy. */

export const INSURANCE_SECTIONS = [
  {
    id: 'life',
    n: 1,
    title: 'Life Insurance',
    navTitle: 'Life Insurance',
    summary: 'Coverage that pays a benefit when someone dies — protecting families, businesses, and financial obligations.',
    status: 'live',
    hub: '/insurance/life',
    accent: 'rose',
    icon: 'HeartPulse',
    products: [
      { name: 'Term Life Insurance', hint: 'Pure protection for a fixed period — affordable, straightforward coverage', href: '/insurance/life/level-term' },
      { name: 'Whole Life Insurance', hint: 'Lifelong coverage with a guaranteed savings component', href: '/insurance/life/traditional-whole-life' },
      { name: 'Universal Life Insurance', hint: 'Flexible coverage with adjustable premiums and savings growth', href: '/insurance/life/universal-life' },
      { name: 'Endowment Plans', hint: 'Insurance plus a guaranteed payout at the end of the term', href: '/insurance/life/full-with-profit-endowment' },
      { name: 'Unit-Linked Insurance Plans (ULIPs)', hint: 'Life cover combined with market-linked investment options', href: '/insurance/life/regular-premium-ulip' },
      { name: 'Money-Back Policies', hint: 'Regular payouts during the term plus a final benefit', href: '/insurance/life/traditional-money-back' },
      { name: 'Annuities & Pension', hint: 'A steady income stream after retirement', href: '/insurance/life/immediate-annuity' },
    ],
  },
  {
    id: 'health',
    n: 2,
    title: 'Health Insurance',
    navTitle: 'Health Insurance',
    summary: 'Medical coverage for individuals, families, seniors, and groups — from routine care to critical illness.',
    status: 'live',
    hub: '/insurance/health',
    accent: 'teal',
    icon: 'Stethoscope',
    products: [
      { name: 'Individual Health', hint: 'Medical coverage for one person', href: '/insurance/health/individual-basic' },
      { name: 'Family Floater', hint: 'One plan that covers your whole family', href: '/insurance/health/family-floater-standard' },
      { name: 'Critical Illness', hint: 'A lump-sum payment when a serious illness is diagnosed', href: '/insurance/health/critical-illness-standalone' },
      { name: 'Senior Citizen Health', hint: 'Medical coverage designed for older adults', href: '/insurance/health/senior-standard' },
      { name: 'Group / Corporate Health', hint: 'Employer-provided medical coverage for employees', href: '/insurance/health/group-employer-mediclaim' },
      { name: 'Top-Up / Super Top-Up', hint: 'Additional coverage that kicks in after a base limit', href: '/insurance/health/super-topup-plan' },
      { name: 'Personal Accident', hint: 'Protection against accidental injury or death', href: '/insurance/health/pa-individual' },
      { name: 'Disability Insurance', hint: 'Income replacement if you cannot work due to injury', href: '/insurance/health/disability-income' },
    ],
  },
  {
    id: 'general',
    n: 3,
    title: 'Personal Lines (P&C)',
    navTitle: 'Personal Lines',
    summary: 'Protect your car, home, travel, and personal assets from everyday risks.',
    status: 'live',
    hub: '/insurance/general',
    accent: 'sky',
    icon: 'Umbrella',
    filterCategories: ['motor', 'home', 'travel', 'marine', 'fire', 'liability', 'cyber'],
    hubKind: 'general',
    products: [
      { name: 'Motor', cat: 'motor', hint: 'Car, motorcycle, or commercial vehicle coverage', href: '/insurance/general/car-tp' },
      { name: 'Home / Property', cat: 'home', hint: 'Protect your home structure and belongings', href: '/insurance/general/home-comprehensive' },
      { name: 'Travel', cat: 'travel', hint: 'Trip cancellation, medical, and baggage protection', href: '/insurance/general/travel-international' },
      { name: 'Marine', cat: 'marine', hint: 'Coverage for goods in transit and shipping', href: '/insurance/general/marine-cargo' },
      { name: 'Fire', cat: 'fire', hint: 'Protection against fire and related disasters', href: '/insurance/general/fire-residential' },
      { name: 'Liability', cat: 'liability', hint: 'Protection if someone sues you for injury or damage', href: '/insurance/general/professional-indemnity-gi' },
      { name: 'Cyber', cat: 'cyber', hint: 'Protection against data breaches and online attacks', href: '/insurance/general/cyber-data-breach' },
    ],
  },
  {
    id: 'commercial',
    n: 4,
    title: 'Commercial Lines',
    navTitle: 'Commercial Lines',
    summary: 'Protect your business — property, employees, leadership, and professional services.',
    status: 'live',
    hub: '/insurance/commercial',
    accent: 'brand',
    icon: 'Briefcase',
    hubKind: 'commercial',
    filterIds: ['property_bi', 'directors_officers', 'workers_comp', 'trade_credit', 'errors_omissions', 'key_person'],
    products: [
      { name: 'Property & Business Interruption', hint: 'Covers your buildings, equipment, and lost income from disruptions', href: '/insurance/commercial/property-bi' },
      { name: 'Directors & Officers (D&O)', hint: 'Protects company leaders from personal liability', href: '/insurance/commercial/do' },
      { name: "Workers' Compensation", hint: 'Covers employee injuries and workplace illnesses', href: '/insurance/commercial/workers-comp' },
      { name: 'Trade Credit', hint: 'Protects against customer non-payment', href: '/insurance/commercial/trade-credit' },
      { name: 'Errors & Omissions (E&O)', hint: 'Protects against claims of professional mistakes', href: '/insurance/commercial/eo' },
      { name: 'Key Person', hint: 'Coverage on a critical employee your business depends on', href: '/insurance/commercial/key-person' },
    ],
  },
  {
    id: 'specialty',
    n: 5,
    title: 'Specialty Lines',
    navTitle: 'Specialty Lines',
    summary: 'Coverage for farms, animals, events, property titles, and mortgage guarantees.',
    status: 'live',
    disabled: true,
    hub: '/insurance/general',
    accent: 'amber',
    icon: 'Leaf',
    filterCategories: ['crop', 'animal', 'event', 'title', 'mortgage_gi'],
    hubKind: 'general',
    products: [
      { name: 'Crop insurance', hint: 'Yield-based and weather-index', href: '/insurance/general/crop-yield' },
      { name: 'Livestock / cattle', hint: 'Vet cert, tag, valuation', href: '/insurance/general/livestock-cattle' },
      { name: 'Pet insurance', hint: 'Vaccination and medical history', href: '/insurance/general/pet-insurance' },
      { name: 'Event insurance', hint: 'Weddings, concerts, public events', href: '/insurance/general/wedding-insurance' },
      { name: 'Title insurance', hint: 'Deed chain, encumbrance, title search', href: '/insurance/general/title-insurance' },
      { name: 'Mortgage insurance', hint: 'Lender-linked cover on the loan / property', href: '/insurance/general/mortgage-insurance-gi' },
    ],
  },
  {
    id: 'provider',
    n: 6,
    title: 'Admitted, Surplus & Reinsurance',
    navTitle: 'Admitted & Reinsurance',
    summary: 'Licensed carriers, surplus lines, and reinsurance arrangements.',
    status: 'live',
    disabled: true,
    hub: '/insurance/general',
    accent: 'violet',
    icon: 'Landmark',
    filterCategories: ['provider'],
    hubKind: 'general',
    products: [
      { name: 'Public sector insurers', hint: 'Govt-backed — strict KYC, often Aadhaar-linked', href: '/insurance/general/insurer-psu' },
      { name: 'Private insurers', hint: 'e-KYC; income proof for higher SI', href: '/insurance/general/insurer-private' },
      { name: 'Reinsurance companies', hint: 'Insurance for insurers — treaty / facultative, not retail KYC', href: '/insurance/general/reinsurance-treaty' },
      { name: 'Bancassurance', hint: 'Distribution channel (sold through banks), not a product type', href: '/insurance/sections/provider' },
    ],
  },
  {
    id: 'engineering',
    n: 7,
    title: 'Engineering & Construction',
    navTitle: 'Engineering & Construction',
    summary: 'Protection for construction projects, equipment, and machinery.',
    status: 'live',
    disabled: true,
    hub: '/insurance/commercial',
    accent: 'orange',
    icon: 'HardHat',
    hubKind: 'commercial',
    filterIds: ['construction', 'builders_risk', 'equipment_breakdown', 'business_interruption'],
    products: [
      { name: "Contractor's All Risk (CAR)", hint: 'Covers construction projects', href: '/insurance/commercial/construction' },
      { name: 'Erection All Risk (EAR)', hint: 'Machinery installation / erection', href: '/insurance/commercial/construction' },
      { name: 'Machinery breakdown', hint: 'Sudden mechanical / electrical failure', href: '/insurance/commercial/equipment-breakdown' },
      { name: 'Boiler & pressure plant', hint: 'Explosion / collapse of pressure equipment', href: '/insurance/commercial/equipment-breakdown' },
      { name: 'Advance Loss of Profit (ALOP)', hint: 'Delay in start-up after a CAR/EAR loss', href: '/insurance/commercial/business-interruption' },
    ],
  },
  {
    id: 'aviation',
    n: 8,
    title: 'Aviation',
    navTitle: 'Aviation',
    summary: 'Aircraft damage, liability, and passenger injury coverage.',
    status: 'live',
    disabled: true,
    hub: '/insurance/commercial/aviation',
    accent: 'indigo',
    icon: 'Plane',
    hubKind: 'commercial',
    filterIds: ['aviation'],
    products: [
      { name: 'Aircraft hull', hint: 'Physical damage to the aircraft', href: '/insurance/commercial/aviation' },
      { name: 'Aviation liability', hint: 'Third-party BI / PD from aircraft operations', href: '/insurance/commercial/aviation' },
      { name: 'Passenger liability', hint: 'Passenger injury / death risk', href: '/insurance/commercial/aviation' },
    ],
  },
  {
    id: 'fidelity',
    n: 9,
    title: 'Crime: Fidelity & Burglary',
    navTitle: 'Crime & Fidelity',
    summary: 'Protection against employee fraud, theft, and burglary.',
    status: 'live',
    disabled: true,
    hub: '/insurance/commercial/crime',
    accent: 'fuchsia',
    icon: 'Lock',
    hubKind: 'commercial',
    filterIds: ['crime'],
    products: [
      { name: 'Fidelity guarantee', hint: 'Employee dishonesty / fraud', href: '/insurance/commercial/crime' },
      { name: 'Burglary / theft', hint: 'Forcible entry and theft of contents', href: '/insurance/commercial/crime' },
    ],
  },
  {
    id: 'catastrophe',
    n: 10,
    title: 'Catastrophe',
    navTitle: 'Catastrophe',
    summary: 'Coverage for natural disasters — floods, earthquakes, and weather events.',
    status: 'live',
    disabled: true,
    hub: '/insurance/commercial',
    accent: 'cyan',
    icon: 'CloudRain',
    hubKind: 'mixed',
    products: [
      { name: 'Flood insurance', hint: 'Inundation damage to property', href: '/insurance/commercial/flood-commercial' },
      { name: 'Earthquake insurance', hint: 'Shake, fire-following, and sprinkler leakage', href: '/insurance/commercial/earthquake-commercial' },
      { name: 'Parametric / weather-index', hint: 'Payout from weather data, not loss adjustment', href: '/insurance/general/crop-weather' },
    ],
  },
  {
    id: 'niche-liability',
    n: 11,
    title: 'Excess & Niche Liability',
    navTitle: 'Excess & Niche Liability',
    summary: 'Extra liability protection, pollution, kidnapping, and political risk coverage.',
    status: 'live',
    disabled: true,
    hub: '/insurance/commercial',
    accent: 'emerald',
    icon: 'Scale',
    hubKind: 'commercial',
    filterIds: ['umbrella', 'pollution', 'kidnap_ransom', 'political_risk', 'terrorism'],
    products: [
      { name: 'Umbrella insurance', hint: 'Extra liability above existing limits', href: '/insurance/commercial/umbrella' },
      { name: 'Environmental / pollution liability', hint: 'Pollution incidents and cleanup', href: '/insurance/commercial/pollution' },
      { name: 'Kidnap & ransom (K&R)', hint: 'Kidnap, extortion, and related crisis costs', href: '/insurance/commercial/kidnap-ransom' },
      { name: 'Political risk', hint: 'Expropriation, transfer, and political violence', href: '/insurance/commercial/political-risk' },
      { name: 'Terrorism insurance', hint: 'Certified terrorism property / liability', href: '/insurance/commercial/terrorism' },
    ],
  },
  {
    id: 'warranty-financial-emerging',
    n: 12,
    title: 'Warranty, Surety & Emerging',
    navTitle: 'Warranty, Surety & Emerging',
    summary: 'Extended warranties, surety bonds, gadgets, credit life, and emerging insurance products.',
    status: 'live',
    disabled: true,
    hub: '/insurance/commercial',
    accent: 'lime',
    icon: 'ShieldCheck',
    hubKind: 'mixed',
    products: [
      { name: 'Extended warranty', hint: 'Electronics, appliances, vehicles beyond OEM warranty', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'Surety bonds', hint: 'Guarantees contract performance (adjacent to insurance)', href: '/insurance/commercial/surety-bonds' },
      { name: 'Gadget / mobile insurance', hint: 'Phones, laptops, wearables — theft, damage, liquid', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'Jewelry / valuables', hint: 'Scheduled high-value personal articles', href: '/insurance/general/home-contents' },
      { name: 'Legal expense insurance', hint: 'Legal costs and defence', href: '/insurance/commercial/legal-expense' },
      { name: 'Credit life', hint: 'Pays off a loan if the borrower dies', href: '/insurance/life/credit-life' },
      { name: 'Bancassurance', hint: 'Insurance sold through banks (channel, not a product)', href: '/insurance/sections/provider' },
      { name: 'Microinsurance', hint: 'Low-premium, low-cover plans for low-income groups', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'On-demand insurance', hint: 'Pay-per-use — a single trip or item', href: '/insurance/sections/warranty-financial-emerging' },
      { name: 'Usage-based motor (telematics)', hint: 'Premium tied to actual driving behaviour', href: '/insurance/general/car-comprehensive' },
      { name: 'Personal cyber', hint: 'Identity theft and online fraud for individuals', href: '/insurance/general/cyber-data-breach' },
    ],
  },
];

export function getInsuranceSection(id) {
  return INSURANCE_SECTIONS.find((s) => s.id === id) || null;
}

export const INSURANCE_NAV_CHILDREN = [
  { to: '/insurance', label: 'All active sections' },
  ...INSURANCE_SECTIONS.map((section) => ({
    to: section.disabled ? undefined : `/insurance/sections/${section.id}`,
    label: `${section.n}. ${section.navTitle || section.title}`,
    tag: section.disabled ? 'Soon' : section.status === 'live' ? 'Live' : 'Catalog',
    sectionId: section.id,
    disabled: section.disabled,
  })),
];

export function insuranceSectionAccent(accent) {
  const map = {
    rose: { ring: 'hover:ring-rose-400/40', iconBg: 'bg-rose-500/15 text-rose-400', tag: 'text-rose-400', num: 'text-rose-400/80', dot: 'bg-rose-400' },
    teal: { ring: 'hover:ring-teal-400/40', iconBg: 'bg-teal-500/15 text-teal-400', tag: 'text-teal-400', num: 'text-teal-400/80', dot: 'bg-teal-400' },
    sky: { ring: 'hover:ring-sky-400/40', iconBg: 'bg-sky-500/15 text-sky-400', tag: 'text-sky-400', num: 'text-sky-400/80', dot: 'bg-sky-400' },
    brand: { ring: 'hover:ring-brand/40', iconBg: 'bg-brand/15 text-brand', tag: 'text-brand', num: 'text-brand/80', dot: 'bg-brand' },
    amber: { ring: 'hover:ring-amber-400/40', iconBg: 'bg-amber-500/15 text-amber-400', tag: 'text-amber-400', num: 'text-amber-400/80', dot: 'bg-amber-400' },
    violet: { ring: 'hover:ring-violet-400/40', iconBg: 'bg-violet-500/15 text-violet-400', tag: 'text-violet-400', num: 'text-violet-400/80', dot: 'bg-violet-400' },
    orange: { ring: 'hover:ring-orange-400/40', iconBg: 'bg-orange-500/15 text-orange-400', tag: 'text-orange-400', num: 'text-orange-400/80', dot: 'bg-orange-400' },
    indigo: { ring: 'hover:ring-indigo-400/40', iconBg: 'bg-indigo-500/15 text-indigo-400', tag: 'text-indigo-400', num: 'text-indigo-400/80', dot: 'bg-indigo-400' },
    fuchsia: { ring: 'hover:ring-fuchsia-400/40', iconBg: 'bg-fuchsia-500/15 text-fuchsia-400', tag: 'text-fuchsia-400', num: 'text-fuchsia-400/80', dot: 'bg-fuchsia-400' },
    cyan: { ring: 'hover:ring-cyan-400/40', iconBg: 'bg-cyan-500/15 text-cyan-400', tag: 'text-cyan-400', num: 'text-cyan-400/80', dot: 'bg-cyan-400' },
    emerald: { ring: 'hover:ring-emerald-400/40', iconBg: 'bg-emerald-500/15 text-emerald-400', tag: 'text-emerald-400', num: 'text-emerald-400/80', dot: 'bg-emerald-400' },
    lime: { ring: 'hover:ring-lime-400/40', iconBg: 'bg-lime-500/15 text-lime-400', tag: 'text-lime-400', num: 'text-lime-400/80', dot: 'bg-lime-400' },
    slate: { ring: 'hover:ring-slate-400/40', iconBg: 'bg-slate-500/15 text-slate-300', tag: 'text-slate-300', num: 'text-slate-400', dot: 'bg-slate-400' },
  };
  return map[accent] || map.slate;
}
